// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Students.Repository;

#nullable disable

namespace Students.Migrations.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20250217201948_SeedTeachers")]
    partial class SeedTeachers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Students.Repository.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Aaron",
                            Gender = 0,
                            LastName = "Hanwell"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Quest",
                            Gender = 0,
                            LastName = "Ball"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Caroline",
                            Gender = 1,
                            LastName = "Turner"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Clorie",
                            Gender = 1,
                            LastName = "Hanwell"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Pecca",
                            Gender = 2,
                            LastName = "Owell"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Bad",
                            Gender = 1,
                            LastName = "Apple"
                        });
                });

            modelBuilder.Entity("Students.Repository.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Micah",
                            LastName = "Davies"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Ben",
                            LastName = "Foster"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Cameron",
                            LastName = "Mason"
                        },
                        new
                        {
                            TeacherId = 4,
                            FirstName = "Zac",
                            LastName = "Cooke"
                        },
                        new
                        {
                            TeacherId = 5,
                            FirstName = "Robbie",
                            LastName = "Fox"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
